accessing
exceptionHandler: anExceptionHandler
	exceptionHandler := anExceptionHandler