testing
handles: anError

	^self exception handles: anError