exception-handling
handle: anError

	self flag: 'TODO:do the ensure magic here..
	instead of ^ there is resume: that trigger all the unwind block in Pharo
	I think there should be some gotoContext changes here'.
	^self block cull: anError